services:

  camera-sony-local:
    class: wlatanowicz\AppBundle\Hardware\Local\SonyCamera
    arguments:
      - '@sys-process'
      - '@sys-filesystem'
      - '@factory-sony-exposure-time'
      - '%gphoto_bin%'
      - '/tmp'
      - '@logger'
    tags:
      - { name: logger.metadata, color: green, display: 'Sony Camera' }

  camera-nikon-local:
    class: wlatanowicz\AppBundle\Hardware\Local\NikonCamera
    arguments:
      - '@sys-process'
      - '@sys-filesystem'
      - '@factory-nikon-exposure-time'
      - '%gphoto_bin%'
      - '/tmp'
      - '@logger'
    tags:
      - { name: logger.metadata, color: green, display: 'Nikon Camera' }

  camera-sony-remote:
    class: wlatanowicz\AppBundle\Hardware\Remote\Camera
    arguments:
      - '@camera-sony-remote-client'
      - '@jms_serializer'
      - '@logger'
    tags:
      - { name: logger.metadata, color: green, display: 'Remote Sony Camera' }

  camera-sony-remote-client:
    class: GuzzleHttp\Client
    arguments:
      -
        base_uri: '%camera_uri%/sony/'

  camera-nikon-remote:
    class: wlatanowicz\AppBundle\Hardware\Remote\Camera
    arguments:
      - '@camera-nikon-remote-client'
      - '@jms_serializer'
      - '@logger'
    tags:
      - { name: logger.metadata, color: green, display: 'Remote Nikon Camera' }

  camera-nikon-remote-client:
    class: GuzzleHttp\Client
    arguments:
      -
        base_uri: '%camera_uri%/nikon/'

  camera-sim:
    class: wlatanowicz\AppBundle\Hardware\Simulator\Camera
    arguments:
      - '@focuser-sim'
      - '@sys-filesystem'
      - '@factory-imagick-image'
      - 'star.jpg'
      - '@logger'
    tags:
      - { name: logger.metadata, color: green, display: 'Camera Simulator' }

  camera-sim-shift:
    class: wlatanowicz\AppBundle\Hardware\Simulator\ShiftCamera
    arguments:
      - '@telescope-sim'
      - '@sys-filesystem'
      - '@factory-imagick-image'
      - 'stars.jpg'
      - '@logger'
    tags:
      - { name: logger.metadata, color: green, display: 'Camera Simulator' }

  camera-sim-real:
    class: wlatanowicz\AppBundle\Hardware\Simulator\RealCamera
    arguments:
      - '@focuser-sim'
      - '@sys-filesystem'
      - '@logger'
    tags:
      - { name: logger.metadata, color: green, display: 'Camera Simulator' }

  camera-sim-fast:
    class: wlatanowicz\AppBundle\Hardware\Simulator\SimpleCamera
    arguments:
      - '@sys-filesystem'
      - '@factory-imagick-image'
      - 'star.jpg'
      - '@logger'
    tags:
      - { name: logger.metadata, color: green, display: 'Camera Simulator' }


  camera-provider:
    class: wlatanowicz\AppBundle\Hardware\Provider\CameraProvider
    arguments:
      -
        local: '@camera-sony-local'
        sony: '@camera-sony-local'
        nikon: '@camera-nikon-local'
        remote-sony: '@camera-sony-remote'
        remote-nikon: '@camera-nikon-remote'
        sim: '@camera-sim'
        sim-fast: '@camera-sim-fast'
        sim-real: '@camera-sim-real'
        sim-shift: '@camera-sim-shift'
      - "%default_camera%"
