services:

  camera-local:
    class: wlatanowicz\AppBundle\Hardware\Local\Camera
    arguments:
      - '@sys-process'
      - '@sys-filesystem'
      - '/usr/local/bin/gphoto2'
      - '/tmp'
      - '@logger'
      - 'Sony Camera'

  camera-remote:
    class: wlatanowicz\AppBundle\Hardware\Remote\Camera
    arguments:
      - '@camera-remote-client'
      - '@jms_serializer'
      - '@logger'
      - 'Remote Camera'

  camera-remote-client:
    class: GuzzleHttp\Client
    arguments:
      -
        base_uri: 'http://192.168.0.50/camera/sony/'

  camera-dummy:
    class: wlatanowicz\AppBundle\Hardware\Dummy\Camera

  camera-sim:
    class: wlatanowicz\AppBundle\Hardware\Simulator\Camera
    arguments:
      - '@focuser-sim'
      - '@sys-filesystem'
      - 'star.jpg'
      - '@logger'
      - 'Camera Simulator'


  camera-provider:
    class: wlatanowicz\AppBundle\Hardware\Provider\CameraProvider
    arguments:
      -
        local: '@camera-local'
        sony: '@camera-local'
        remote: '@camera-remote'
        dummy: '@camera-dummy'
        sim: '@camera-sim'
