services:

  camera-local:
    class: wlatanowicz\AppBundle\Hardware\Local\Camera
    arguments:
      - '@sys-process'
      - '@sys-filesystem'
      - 'umask 0000 && sudo /usr/local/bin/gphoto2'
      - '/tmp'
      - '@logger'
    tags:
      - { name: logger.metadata, color: green, display: 'Sony Camera' }

  camera-remote:
    class: wlatanowicz\AppBundle\Hardware\Remote\Camera
    arguments:
      - '@camera-remote-client'
      - '@jms_serializer'
      - '@logger'
    tags:
      - { name: logger.metadata, color: green, display: 'Remote Camera' }

  camera-remote-client:
    class: GuzzleHttp\Client
    arguments:
      -
        base_uri: 'http://192.168.0.50/index.php/hardware/camera/sony/'

  camera-sim:
    class: wlatanowicz\AppBundle\Hardware\Simulator\Camera
    arguments:
      - '@focuser-sim'
      - '@sys-filesystem'
      - '@factory-imagick-image'
      - 'star.jpg'
      - '@logger'
    tags:
      - { name: logger.metadata, color: green, display: 'Camera Simulator' }

  camera-sim-fast:
    class: wlatanowicz\AppBundle\Hardware\Simulator\SimpleCamera
    arguments:
      - '@sys-filesystem'
      - 'star.jpg'
      - '@logger'
    tags:
      - { name: logger.metadata, color: green, display: 'Camera Simulator' }


  camera-provider:
    class: wlatanowicz\AppBundle\Hardware\Provider\CameraProvider
    arguments:
      -
        local: '@camera-local'
        sony: '@camera-local'
        remote: '@camera-remote'
        sim: '@camera-sim'
        sim-fast: '@camera-sim-fast'
      - "%default_camera%"
