services:

  focuser-node:
    class: wlatanowicz\AppBundle\Hardware\Local\Focuser
    arguments:
      - '@focuser-node-http-client'
      - '@logger'
    tags:
      - { name: logger.metadata, color: red, display: 'Node Focuser' }

  focuser-node-http-client:
    class: GuzzleHttp\Client
    arguments:
      -
        base_uri: 'http://192.168.0.51/'

  focuser-dummy:
    class: wlatanowicz\AppBundle\Hardware\Dummy\Focuser

  focuser-sim:
    class: wlatanowicz\AppBundle\Hardware\Simulator\Focuser
    arguments:
      - 500
      - '@logger'
    tags:
      - { name: logger.metadata, color: red, display: 'Focuser Simulator' }


  focuser-provider:
    class: wlatanowicz\AppBundle\Hardware\Provider\FocuserProvider
    arguments:
      -
        node: '@focuser-node'
        dummy: '@focuser-dummy'
        sim: '@focuser-sim'
      - "%default_focuser%"
