services:

  gd-camera-dummy:
    class: wlatanowicz\AppBundle\Hardware\Wrapper\GdCamera
    arguments:
      - '@camera-dummy'

  gd-camera-local:
    class: wlatanowicz\AppBundle\Hardware\Wrapper\GdCamera
    arguments:
      - '@camera-local'

  gd-camera-sim:
    class: wlatanowicz\AppBundle\Hardware\Simulator\GdCamera
    arguments:
      - '@focuser-sim'

  gd-cropped-dummy:
    class: wlatanowicz\AppBundle\Hardware\Wrapper\GdCircleCroppingCamera
    arguments:
      - '@gd-camera-dummy'

  gd-cropped-local:
    class: wlatanowicz\AppBundle\Hardware\Wrapper\GdCircleCroppingCamera
    arguments:
      - '@gd-camera-local'

  gd-cropped-sim:
    class: wlatanowicz\AppBundle\Hardware\Wrapper\GdCircleCroppingCamera
    arguments:
      - '@gd-camera-sim'


  camera-provider:
    class: wlatanowicz\AppBundle\Hardware\Provider\GdCameraProvider
    arguments:
      -
        dummy: '@gd-cropped-dummy'
        local: '@gd-cropped-local'
        sim: '@gd-cropped-sim'