services:

  imagick-camera-local:
    class: wlatanowicz\AppBundle\Hardware\Wrapper\ImagickCamera
    arguments:
      - '@camera-local'
      - '@factory-imagick-image'

  imagick-camera-remote:
    class: wlatanowicz\AppBundle\Hardware\Wrapper\ImagickCamera
    arguments:
      - '@camera-remote'
      - '@factory-imagick-image'

  imagick-camera-sim:
    class: wlatanowicz\AppBundle\Hardware\Wrapper\ImagickCamera
    arguments:
      - '@camera-sim'
      - '@factory-imagick-image'

  imagick-cropped-local:
    class: wlatanowicz\AppBundle\Hardware\Wrapper\ImagickCircleCroppingCamera
    arguments:
      - '@imagick-camera-local'

  imagick-cropped-remote:
    class: wlatanowicz\AppBundle\Hardware\Wrapper\ImagickCircleCroppingCamera
    arguments:
      - '@imagick-camera-remote'

  imagick-cropped-sim:
    class: wlatanowicz\AppBundle\Hardware\Wrapper\ImagickCircleCroppingCamera
    arguments:
      - '@imagick-camera-sim'


  imagick-camera-provider:
    class: wlatanowicz\AppBundle\Hardware\Provider\ImagickCroppedCameraProvider
    arguments:
      -
        sony-local: '@imagick-cropped-local'
        sony-remote: '@imagick-cropped-remote'
        sim: '@imagick-cropped-sim'
      - "%default_camera%"
