services:
  telescope-local:
    class: wlatanowicz\AppBundle\Hardware\Local\Telescope
    arguments:
      - '@telescope-local-mount'

  telescope-local-mount:
    class: wlatanowicz\AppBundle\Hardware\Local\TelescopeMount
    arguments:
      - '@telescope-local-mount-serial'

  telescope-local-mount-serial:
    class: wlatanowicz\AppBundle\Hardware\Helper\SerialPort
    arguments:
      - '@sys-process'
      - '/dev/ttyUSB0'

  telescope-remote:
    class: wlatanowicz\AppBundle\Hardware\Remote\Telescope
    arguments:
      - '@telescope-remote-client'
      - '@jms_serializer'

  telescope-stellarium:
    class: wlatanowicz\AppBundle\Hardware\Local\StellariumTelescope
    arguments:
      - '192.168.0.21'
      - 10001

  telescope-sim:
    class: wlatanowicz\AppBundle\Hardware\Simulator\Telescope
    arguments:
      - 500
      - '%kernel.cache_dir%/state/telescope-simulator'
      - '@logger'
      - '@sys-filesystem'
      - '@jms_serializer'

  telescope-remote-client:
    class: GuzzleHttp\Client
    arguments:
      -
        base_uri: 'http://192.168.0.50/index.php/hardware/telescope/sw/'

  telescope-provider:
    class: wlatanowicz\AppBundle\Hardware\Provider\TelescopeProvider
    arguments:
      -
        sim: '@telescope-sim'
        local: '@telescope-local'
        sw: '@telescope-local'
        stellarium: '@telescope-stellarium'
        remote: '@telescope-remote'
      - "%default_telescope%"
