services:
  telescope-local:
    class: wlatanowicz\AppBundle\Hardware\Local\Telescope
    arguments:
      - '@telescope-local-mount'

  telescope-local-mount:
    class: wlatanowicz\AppBundle\Hardware\Local\TelescopeMount
    arguments:
      - '@telescope-local-mount-serial'

  telescope-local-mount-serial:
    class: wlatanowicz\AppBundle\Hardware\Helper\SerialPort
    arguments:
      - '/dev/ttyUSB0'

  telescope-remote:
    class: wlatanowicz\AppBundle\Hardware\Remote\Telescope
    arguments:
      - '@camera-remote-client'
      - '@jms_serializer'

  telescope-remote-client:
    class: GuzzleHttp\Client
    arguments:
      -
        base_uri: 'http://192.168.0.50/telescope/sw/'

  telescope-provider:
    class: wlatanowicz\AppBundle\Hardware\Provider\TelescopeProvider
    arguments:
      -
        local: '@telescope-local'
        sw: '@telescope-local'
        remote: '@telescope-remote'
