services:
  command-telesope-goto:
    class: wlatanowicz\AppBundle\Command\Telescope\GotoCommand
    arguments:
      - '@job-telescope-set-position'
    tags:
        - { name: console.command }

  command-telesope-position:
    class: wlatanowicz\AppBundle\Command\Telescope\PositionCommand
    arguments:
      - '@job-telescope-get-position'
    tags:
        - { name: console.command }

  command-focuser-goto:
    class: wlatanowicz\AppBundle\Command\Focuser\GotoCommand
    arguments:
      - '@job-focuser-set-position'
    tags:
        - { name: console.command }

  command-camera-expose:
    class: wlatanowicz\AppBundle\Command\Camera\ExposeCommand
    arguments:
      - '@job-camera-expose'
      - '@factory-float-from-string'
    tags:
        - { name: console.command }

  command-camera-setup:
    class: wlatanowicz\AppBundle\Command\Camera\SetupCommand
    arguments:
      - '@camera-provider'
      - '@logger'
    tags:
        - { name: console.command }

  command-focuser-autofocus:
    class: wlatanowicz\AppBundle\Command\Focuser\AutofocusCommand
    arguments:
      - '@job-autofocus'
    tags:
        - { name: console.command }

  command-focuser-measure:
    class: wlatanowicz\AppBundle\Command\Focuser\MeasureCommand
    arguments:
      - '@camera-provider'
      - '@focuser-provider'
      - '@image-processing-af-report-generator'
      - '@logger'
    tags:
        - { name: console.command }

