services:
  command-goto:
    class: wlatanowicz\AppBundle\Command\Telescope\GotoCommand
    arguments:
      - '@telescope-provider'
    tags:
        - { name: console.command }

  command-focuser:
    class: wlatanowicz\AppBundle\Command\Focuser\GotoCommand
    arguments:
      - '@focuser-provider'
    tags:
        - { name: console.command }

  command-camera-expose:
    class: wlatanowicz\AppBundle\Command\Camera\ExposeCommand
    arguments:
      - '@camera-provider'
      - '@sys-filesystem'
    tags:
        - { name: console.command }
