services:
  command-goto:
    class: wlatanowicz\AppBundle\Command\Telescope\GotoCommand
    arguments:
      - '@telescope-provider'
    tags:
        - { name: console.command }

  command-focuser-goto:
    class: wlatanowicz\AppBundle\Command\Focuser\GotoCommand
    arguments:
      - '@focuser-provider'
    tags:
        - { name: console.command }

  command-camera-expose:
    class: wlatanowicz\AppBundle\Command\Camera\ExposeCommand
    arguments:
      - '@camera-provider'
      - '@sys-filesystem'
    tags:
        - { name: console.command }

  command-camera-setup:
    class: wlatanowicz\AppBundle\Command\Camera\SetupCommand
    arguments:
      - '@camera-provider'
    tags:
        - { name: console.command }

  command-focuser-autofocus:
    class: wlatanowicz\AppBundle\Command\Focuser\AutofocusCommand
    arguments:
      - '@imagick-camera-provider'
      - '@focuser-provider'
      - '@measure-provider'
      - '@autofocus-default'
      - '@logger'
    tags:
        - { name: console.command }

  command-focuser-measure:
    class: wlatanowicz\AppBundle\Command\Focuser\MeasureCommand
    arguments:
      - '@imagick-camera-provider'
      - '@focuser-provider'
      - '@logger'
    tags:
        - { name: console.command }
