services:
  command-goto:
    class: wlatanowicz\AppBundle\Command\TelescopeCommand
    arguments:
      - '@telescope-local'
    tags:
        - { name: console.command }

  command-focuser:
    class: wlatanowicz\AppBundle\Command\FocuserCommand
    arguments:
      - '@focuser-provider'
    tags:
        - { name: console.command }
