# app/config/services.yml
services:
  ctrl-info:
    class: wlatanowicz\AppBundle\Api\Controller\Info

  ctrl-camera-image:
    class: wlatanowicz\AppBundle\Api\Controller\Camera\Image
    arguments:
      - '@camera-provider'
      - '@jms_serializer'