# app/config/services.yml
services:
  ctrl-info:
    class: wlatanowicz\AppBundle\Api\Controller\Info

  ctrl-camera-image:
    class: wlatanowicz\AppBundle\Api\Controller\Camera\Image
    arguments:
      - '@camera-provider'
      - '@jms_serializer'

  ctrl-camera-settings:
    class: wlatanowicz\AppBundle\Api\Controller\Camera\Settings
    arguments:
      - '@camera-provider'
      - '@jms_serializer'

  ctrl-focuser-position:
    class: wlatanowicz\AppBundle\Api\Controller\Focuser\Position
    arguments:
      - '@camera-provider'
      - '@jms_serializer'

  ctrl-telescope-position:
    class: wlatanowicz\AppBundle\Api\Controller\Telescope\Position
    arguments:
      - '@telescope-provider'
      - '@jms_serializer'
