services:
  telescope-local:
    class: wlatanowicz\AppBundle\Hardware\Local\Telescope
    arguments:
      - '@telescope-mount'

  telescope-mount:
    class: wlatanowicz\AppBundle\Hardware\Local\TelescopeMount
    arguments:
      - '@telescope-mount-serial'

  telescope-mount-serial:
    class: wlatanowicz\AppBundle\Hardware\Helper\SerialPort
    arguments:
      - '/dev/ttyUSB0'

  camera-local:
    class: wlatanowicz\AppBundle\Hardware\Local\Camera
    arguments:
      - '@sys-process'
      - '@sys-filesystem'
      - '/usr/local/bin/gphoto2'
      - '/tmp'

  camera-dummy:
    class: wlatanowicz\AppBundle\Hardware\Dummy\Camera

  radio-local:
    class: wlatanowicz\AppBundle\Hardware\Local\Radio
    arguments:
      - '@radio-receiver'

  radio-receiver:
    class: wlatanowicz\AppBundle\Hardware\Local\RadioReceiver
    arguments:
      - '@sys-process'
      - '/opt/local/bin/rtl_power'
      - 1

  focuser-node:
    class: wlatanowicz\AppBundle\Hardware\Local\Focuser
    arguments:
      - '@focuser-node-http-client'

  focuser-node-http-client:
    class: GuzzleHttp\Client
    arguments:
      -
        base_uri: 'http://192.168.0.51/'

  focuser-dummy:
    class: wlatanowicz\AppBundle\Hardware\Dummy\Focuser

  telesope-provider:
    class: wlatanowicz\AppBundle\Hardware\Provider\TelescopeProvider
    arguments:
      -
        local: '@telescope-local'

  camera-provider:
    class: wlatanowicz\AppBundle\Hardware\Provider\CameraProvider
    arguments:
      -
        local: '@camera-local'
        dummy: '@camera-dummy'

  radio-provider:
    class: wlatanowicz\AppBundle\Hardware\Provider\RadioProvider
    arguments:
      -
        local: '@radio-local'

  focuser-provider:
    class: wlatanowicz\AppBundle\Hardware\Provider\FocuserProvider
    arguments:
      -
        node: '@focuser-node'
        dummy: '@focuser-dummy'
