services:
  job-autofocus:
    class: wlatanowicz\AppBundle\Job\Autofocus
    arguments:
      - '@job-manager'
      - '@camera-provider'
      - '@focuser-provider'
      - '@measure-provider'
      - '@autofocus-default'
      - '@sys-filesystem'
      - '@image-processing-af-report-generator'
      - '@logger'

  job-telescope-set-position:
    class: wlatanowicz\AppBundle\Job\TelescopeSetPosition
    arguments:
      - '@job-manager'
      - '@telescope-provider'

  job-telescope-get-position:
    class: wlatanowicz\AppBundle\Job\TelescopeGetPosition
    arguments:
      - '@job-manager'
      - '@telescope-provider'

  job-focuser-set-position:
    class: wlatanowicz\AppBundle\Job\FocuserSetPosition
    arguments:
      - '@job-manager'
      - '@focuser-provider'

  job-focuser-get-position:
    class: wlatanowicz\AppBundle\Job\FocuserGetPosition
    arguments:
      - '@job-manager'
      - '@focuser-provider'

  job-camera-expose:
    class: wlatanowicz\AppBundle\Job\CameraExpose
    arguments:
      - '@job-manager'
      - '@camera-provider'

  job-provider:
    class: wlatanowicz\AppBundle\Job\JobProvider
    arguments:
      -
        autofocus: '@job-autofocus'
        telescope.get-position: '@job-telescope-get-position'
        telescope.set-position: '@job-telescope-set-position'
        focuser.get-position: '@job-focuser-get-position'
        focuser.set-position: '@job-focuser-set-position'
        camera.expose: '@job-camera-expose'
