services:
  job-autofocus:
    class: wlatanowicz\AppBundle\Job\Autofocus
    arguments:
      - '@job-manager'
      - '@imagick-camera-provider'
      - '@focuser-provider'
      - '@measure-provider'
      - '@autofocus-default'
      - '@sys-filesystem'
      - '@logger'

  job-provider:
    class: wlatanowicz\AppBundle\Job\JobProvider
    arguments:
      -
        autofocus: '@job-autofocus'
