parameters:
  kernel.secret: ThisIsVerySecret
  default_camera: 'remote-sony'
  default_focuser: 'node'
  default_telescope: 'stellarium'
  default_radio: 'local'
  default_measure: 'radius'
  default_autofocus: 'linear'

  gphoto_bin: 'umask 0000 && sudo /usr/local/bin/gphoto2' #linux

  camera_uri: 'http://192.168.0.50/index.php/hardware/camera'
