parameters:
  kernel.secret: ThisIsVerySecret
  default_camera: 'remote'
  default_iamgick_camera: 'remote'
  default_focuser: 'node'
  default_telescope: 'stellarium'
  default_radio: 'local'
  default_measure: 'fwhm'

  gphoto_bin: 'umask 0000 && sudo /usr/local/bin/gphoto2' #linux
  #gphoto_bin: 'umask 0000 && /opt/local/bin/gphoto2' #mac

  camera_uri: 'http://192.168.0.50/index.php/hardware/camera'
