parameters:
  kernel.secret: ThisIsVerySecret
  default_camera: 'remote'
  default_iamgick_camera: 'remote'
  default_focuser: 'node'
  default_telescope: 'stellarium'
  default_radio: 'local'
  default_measure: 'fwhm'
