services:
  autofocus-default:
    class: wlatanowicz\AppBundle\Routine\AutoFocus\SimpleRecursive
    arguments:
      - '@logger'
      - '@factory-imagick-image'
    tags:
      - { name: logger.metadata, color: blue, display: 'AutoFocus' }

  measure-star-fwhm:
    class: wlatanowicz\AppBundle\Routine\Measure\StarFWHM
    arguments:
      - '@image-processing-crop'
      - 0.03
      - 0.5

  measure-provider:
    class: wlatanowicz\AppBundle\Routine\Provider\MeasureProvider
    arguments:
      -
        fwhm: '@measure-star-fwhm'
      - '%default_measure%'

  image-processing-crop:
    class: wlatanowicz\AppBundle\Routine\ImageProcessing\ImagickCircleCrop

  image-processing-af-report-generator:
    class: wlatanowicz\AppBundle\Routine\ImageProcessing\AutoFocusReportGenerator
    arguments:
      - '@factory-imagick-image'
      - '@image-processing-crop'
