services:
  sys-process:
    class: wlatanowicz\AppBundle\Hardware\Helper\Process

  sys-filesystem:
    class: wlatanowicz\AppBundle\Hardware\Helper\FileSystem

  exception.listener:
    class: wlatanowicz\AppBundle\Helper\LoggingExceptionListener
    arguments:
      - '@logger'
    tags:
      - { name: kernel.event_listener, event: kernel.exception }

  job-log-handler:
    class: wlatanowicz\AppBundle\Helper\JobLogHandler
    arguments:
      - "@job-manager"

  job-manager:
    class: wlatanowicz\AppBundle\Helper\JobManager
    arguments:
      - '@jms_serializer'
      - '@sys-filesystem'
      - "%kernel.sessions_dir%/{sessionId}/jobs/{jobId}.log"
      - "%kernel.sessions_dir%/{sessionId}/jobs/{jobId}.status.json"
      - "%kernel.sessions_dir%/{sessionId}/results"

  factory-sony-exposure-time:
    class: wlatanowicz\AppBundle\Factory\SonyExposureTimeStringFactory
    arguments:
      - '@factory-float-from-string'

  factory-nikon-exposure-time:
    class: wlatanowicz\AppBundle\Factory\NikonExposureTimeStringFactory
    arguments:
      - '@factory-float-from-string'

  factory-float-from-string:
    class: wlatanowicz\AppBundle\Factory\FloatFromStringFactory
