services:
  sys-process:
    class: wlatanowicz\AppBundle\Hardware\Helper\Process

  sys-filesystem:
    class: wlatanowicz\AppBundle\Hardware\Helper\FileSystem

  exception.listener:
    class: wlatanowicz\AppBundle\Helper\LoggingExceptionListener
    arguments:
      - '@logger'
    tags:
      - { name: kernel.event_listener, event: kernel.exception }
