services:
  sys-process:
    class: wlatanowicz\AppBundle\Hardware\Helper\Process

  sys-filesystem:
    class: wlatanowicz\AppBundle\Hardware\Helper\FileSystem

  exception.listener:
    class: wlatanowicz\AppBundle\Helper\LoggingExceptionListener
    arguments:
      - '@logger'
    tags:
      - { name: kernel.event_listener, event: kernel.exception }

  job-log-handler:
    class: wlatanowicz\AppBundle\Helper\JobLogHandler
    arguments:
      - "@job-manager"

  job-manager:
    class: wlatanowicz\AppBundle\Helper\JobManager
    arguments:
      - "%kernel.jobs_dir%/logs"
      - "%kernel.jobs_dir%/statuses"
      - "%kernel.jobs_dir%/results"
