/*{"source":"/htdocs/radio-telescope/contrib/nodemcu-focuser/PhoneRemote/app/View/MainView.tpl","md5":"e3e8b45dddd0d12e31b8872ba00af63b","mtime":"2017-05-10T20:32:00.000Z","date":"2017-05-10T20:32:01.431Z"}*/
import Expression from "/htdocs/radio-telescope/contrib/nodemcu-focuser/PhoneRemote/framework/Expression";
import Content from "/htdocs/radio-telescope/contrib/nodemcu-focuser/PhoneRemote/framework/Content";
import AnimatedRouteView from "/htdocs/radio-telescope/contrib/nodemcu-focuser/PhoneRemote/framework/AnimatedRouteView";
import Button from "/htdocs/radio-telescope/contrib/nodemcu-focuser/PhoneRemote/framework/WebControls/FormControls/Button";
import TextBox from "/htdocs/radio-telescope/contrib/nodemcu-focuser/PhoneRemote/framework/WebControls/FormControls/TextBox";
import PlaceHolder from "/htdocs/radio-telescope/contrib/nodemcu-focuser/PhoneRemote/framework/PlaceHolder";
import ServiceContainer from "/htdocs/radio-telescope/contrib/nodemcu-focuser/PhoneRemote/framework/DependencyInjection/ServiceContainer";

export default function template()
{
	var ExpressionContext = this;
	var SourceTemplateControl = this;
	var c523 = new Content();
	this.addTemplateChildControl( "c523", c523 );
	c523.renderTemplateChildControls = function( placeholder ){
		this._templateControls["c524"].renderContentsInPlaceholder( placeholder );
		this._templateControls["c525"].renderContentsInPlaceholder( placeholder );
		var h_c526 = document.createElement( "div" );
		h_c526.setAttribute( "class", "bar bar-footer bar-light" );
		var h_c527 = document.createElement( "div" );
		h_c527.setAttribute( "class", "title" );
		var t_c528 = document.createTextNode( "\n\t\t"+( new Expression( function(){ return ( this.IP ); }.bind( ExpressionContext ) ) )+"\n\t\t" );
		h_c527.appendChild( t_c528 );
		this._templateControls["c529"].renderContentsInPlaceholder( h_c527 );
		this._templateControls["c530"].renderContentsInPlaceholder( h_c527 );
		h_c526.appendChild( h_c527 );
		placeholder.appendChild( h_c526 );
	};
	var c524 = new AnimatedRouteView();
	c524.Path = "/";
	c523.addTemplateChildControl( "c524", c524 );
	c524.renderTemplateChildControls = function( placeholder ){
		var h_c531 = document.createElement( "div" );
		h_c531.setAttribute( "class", "bar bar-header bar-light" );
		this._templateControls["c532"].renderContentsInPlaceholder( h_c531 );
		var h_c533 = document.createElement( "h1" );
		h_c533.setAttribute( "class", "title" );
		var t_c534 = document.createTextNode( "Fouser Remote" );
		h_c533.appendChild( t_c534 );
		h_c531.appendChild( h_c533 );
		var h_c535 = document.createElement( "a" );
		h_c535.setAttribute( "href", "#/bookmarks" );
		h_c535.setAttribute( "class", "button button-icon icon ion-navicon" );
		h_c531.appendChild( h_c535 );
		placeholder.appendChild( h_c531 );
		var h_c536 = document.createElement( "div" );
		h_c536.setAttribute( "class", "content has-header has-footer padding" );
		var h_c537 = document.createElement( "div" );
		h_c537.setAttribute( "class", "list card" );
		var h_c538 = document.createElement( "label" );
		h_c538.setAttribute( "class", "item range" );
		var h_c539 = document.createElement( "i" );
		h_c539.setAttribute( "class", "icon ion-speedometer" );
		h_c538.appendChild( h_c539 );
		this._templateControls["c540"].renderContentsInPlaceholder( h_c538 );
		h_c537.appendChild( h_c538 );
		this._templateControls["c541"].renderContentsInPlaceholder( h_c537 );
		var h_c542 = document.createElement( "label" );
		h_c542.setAttribute( "class", "item range" );
		var h_c543 = document.createElement( "i" );
		h_c543.setAttribute( "class", "icon ion-arrow-down-a" );
		h_c542.appendChild( h_c543 );
		this._templateControls["c544"].renderContentsInPlaceholder( h_c542 );
		var h_c545 = document.createElement( "i" );
		h_c545.setAttribute( "class", "icon ion-arrow-up-a" );
		h_c542.appendChild( h_c545 );
		h_c537.appendChild( h_c542 );
		h_c536.appendChild( h_c537 );
		this._templateControls["c546"].renderContentsInPlaceholder( h_c536 );
		this._templateControls["c547"].renderContentsInPlaceholder( h_c536 );
		placeholder.appendChild( h_c536 );
	};
	var c532 = new Button();
	c532.CssClass = "button button-icon icon ion-android-favorite";
	c524.addTemplateChildControl( "c532", c532 );
	c532.event.attach( "Click", SourceTemplateControl.addBoomarkClicked.bind( SourceTemplateControl ) );
	var c540 = new TextBox();
	c540.Disabled = ( new Expression( function(){ return ( ! this.Connected ); }.bind( ExpressionContext ) ) );
	c540.ID = "StepSize";
	c540.Type = "range";
	c540.Attributes.min = "1";
	c540.Attributes.max = "1000";
	c540.Text = "100";
	c524.addTemplateChildControl( "c540", c540 );
	var c541 = new PlaceHolder();
	c541.ID = "Position";
	c524.addTemplateChildControl( "c541", c541 );
	c541.renderTemplateChildControls = function( placeholder ){
		var h_c548 = document.createElement( "span" );
		h_c548.setAttribute( "class", "item" );
		var t_c549 = document.createTextNode( "\n                    Current position\n                    " );
		h_c548.appendChild( t_c549 );
		var h_c550 = document.createElement( "span" );
		h_c550.setAttribute( "class", "item-note" );
		var t_c551 = document.createTextNode( "\n                    "+( new Expression( function(){ return ( this.Position ); }.bind( ExpressionContext ) ) )+"\n                    " );
		h_c550.appendChild( t_c551 );
		h_c548.appendChild( h_c550 );
		placeholder.appendChild( h_c548 );
		var h_c552 = document.createElement( "span" );
		h_c552.setAttribute( "class", "item" );
		var t_c553 = document.createTextNode( "\n                    Target position\n                    " );
		h_c552.appendChild( t_c553 );
		var h_c554 = document.createElement( "span" );
		h_c554.setAttribute( "class", "item-note" );
		var t_c555 = document.createTextNode( "\n                    "+( new Expression( function(){ return ( this.TargetPosition ); }.bind( ExpressionContext ) ) )+"\n                    " );
		h_c554.appendChild( t_c555 );
		h_c552.appendChild( h_c554 );
		placeholder.appendChild( h_c552 );
	};
	var c544 = new TextBox();
	c544.Disabled = ( new Expression( function(){ return ( ! this.Connected ); }.bind( ExpressionContext ) ) );
	c544.ID = "PositionSlider";
	c544.Type = "range";
	c544.Attributes.min = ( new Expression( function(){ return ( this.Min ); }.bind( ExpressionContext ) ) );
	c544.Attributes.max = ( new Expression( function(){ return ( this.Max ); }.bind( ExpressionContext ) ) );
	c524.addTemplateChildControl( "c544", c544 );
	c544.event.attach( "Change", SourceTemplateControl.sliderMoved.bind( SourceTemplateControl ) );
	var c546 = new Button();
	c546.Disabled = ( new Expression( function(){ return ( ! this.Connected ); }.bind( ExpressionContext ) ) );
	c546.CssClass = "button button-block button-positive icon-left ion-arrow-down-a position-button";
	c546.Text = "Down";
	c546.CustomData = ( new Expression( function(){ return ( { Direction: 'down' } ); }.bind( ExpressionContext ) ) );
	c524.addTemplateChildControl( "c546", c546 );
	c546.event.attach( "Click", SourceTemplateControl.buttonClicked.bind( SourceTemplateControl ) );
	var c547 = new Button();
	c547.Disabled = ( new Expression( function(){ return ( ! this.Connected ); }.bind( ExpressionContext ) ) );
	c547.CssClass = "button button-block button-positive icon-left ion-arrow-up-a position-button";
	c547.Text = "Up";
	c547.CustomData = ( new Expression( function(){ return ( { Direction: 'up' } ); }.bind( ExpressionContext ) ) );
	c524.addTemplateChildControl( "c547", c547 );
	c547.event.attach( "Click", SourceTemplateControl.buttonClicked.bind( SourceTemplateControl ) );
	var c525 = ServiceContainer.get("view.bookmarks");
	c523.addTemplateChildControl( "c525", c525 );
	var c529 = new PlaceHolder();
	c529.Visible = ( new Expression( function(){ return ( this.Connected); }.bind( ExpressionContext ) ) );
	c523.addTemplateChildControl( "c529", c529 );
	c529.renderTemplateChildControls = function( placeholder ){
		var h_c556 = document.createElement( "i" );
		h_c556.setAttribute( "class", "icon ion-checkmark-circled balanced" );
		placeholder.appendChild( h_c556 );
	};
	var c530 = new PlaceHolder();
	c530.Visible = ( new Expression( function(){ return ( ! this.Connected); }.bind( ExpressionContext ) ) );
	c523.addTemplateChildControl( "c530", c530 );
	c530.renderTemplateChildControls = function( placeholder ){
		var h_c557 = document.createElement( "i" );
		h_c557.setAttribute( "class", "icon ion-close-circled assertive" );
		placeholder.appendChild( h_c557 );
	};
}
