heartbeat:
  path: /heartbeat
  defaults:
    _controller: ctrl-api-heartbeat:getHeartbeat
    _format: json
  methods: [GET]

rpc-start:
  path: /job/{sessionId}/{jobId}
  defaults:
    _controller: ctrl-api-job:start
    _format: json
  methods: [POST]

rpc-status:
  path: /job/{sessionId}/{jobId}
  defaults:
    _controller: ctrl-api-job:status
    _format: json
  methods: [GET]

rpc-logs:
  path: /job/{sessionId}/{jobId}/logs
  defaults:
    _controller: ctrl-api-job:logs
    _format: json
  methods: [GET]

rpc-result:
  path: /job/{sessionId}/results/{filename}
  defaults:
    _controller: ctrl-api-job:result
    _format: json
  methods: [GET]

